### ISSUE TITLE
No update available for Nextcloud 20.0.7

### ISSUE THREAD

**Issue by brot** [nextcloud/twofactor_totp#1074] opened 2021-02-04 08:15 UTC
Will there be an update for the latest released version 20.0.7?

Nextcloud shows me that this App is not compatible with the latest version
![image](https://user-images.githubusercontent.com/36720/106863944-87ef5200-66c9-11eb-97f4-95936c9bb284.png)

**Comment by tlinna** [comment] 2021-02-04 16:32
Duplicate of #1073

**Comment by ChristophWurst** [comment] 2021-02-04 16:41
yeah … just ignore the warning one time :)

**Closed by ChristophWurst** 2021-02-04 16:41 UTC

**Comment by brianWreaves** [comment] 2021-04-04 04:44
I presume it's also ok to update to 20.0.8?
