### ISSUE TITLE
Configurable system time correction

### ISSUE THREAD

**Issue by mithodin** [nextcloud/twofactor_totp#117] opened 2017-01-06 14:54 UTC
Some people need to live on some crappy shared hosting service where they do not care about keeping the system time synchronized. This pretty much breaks totp.
Since the system time is not under my control, I need to fix this in the application. I have already submitted a patch to the otp library (view pull request at https://github.com/ChristianRiesen/otp/pull/15), which adds the possibility to set a static offset via Otp::setTotpOffset().

Now the calling library just has to handle that offset in a sane way (otherwise, an attacker could basically use an arbitrary old password by adjusting the offset accordingly). For twofactor_totp, I see two options:
a) Calculate the offset periodically and store it in the database. Should be configurable by the admin only.
b) Calculate the offset on-the-fly for every login (maybe slower, but not too noticable at least for my setup).

One also needs a precise time source. I have a quick-and-dirty implementation here: https://github.com/mithodin/twofactor_totp that uses ntp via bt51/ntp with option b). I have not had the time to learn enough about nextcloud to implement option a). Ntp would need some way for the admin to configure an ntp-server the admin trusts. Another option may be time.is, if they have an api.

I know that it's not a nice way to handle this, but there are people out there (including me) for whom this is the only way to get totp working.

**Comment by ChristophWurst** [comment] 2017-01-09 10:44
how about c) use a constant time correction, assuming that the time drift does not vary over time? That would be the simplest solution, we could add a parameter to config.php for that.

**Comment by mithodin** [comment] 2017-01-09 10:57
This is a nice assumption that does not hold on every device. I'm writing this on a computer that drifts by about a minute in two months.

**Comment by ChristophWurst** [comment] 2017-01-09 11:52
I see. Then there's really no way around using a NTP I guess, which you proposed already. Do you have time to work on this?

**Comment by mithodin** [comment] 2017-01-09 12:50
Are we talking about option a) then? I will give it a try. Is there a good document that could get me started on how to deal with admin settings in nextcloud?

**Comment by LukasReschke** [comment] 2017-01-09 12:52
> how about c) use a constant time correction, assuming that the time drift does not vary over time? That would be the simplest solution, we could add a parameter to config.php for that.

I'll oppose that very much. It is not the Nextcloud servers responsibility to fix broken setups.

**Comment by MorrisJobke** [comment] 2017-01-09 12:56
> Some people need to live on some crappy shared hosting service where they do not care about keeping the system time synchronized. This pretty much breaks totp.

Then ask the support to fix it. 🙈

**Comment by mithodin** [comment] 2017-01-09 13:08
@MorrisJobke the problem is drift. If they do not have ntp set up, the clock will be out of sync again sooner or later. This is just something that is not under the control of me as a customer on a shared hosting service. I would like to have my own root server but I do not. So I need a way to deal with it that does not break every half a year. If you, @LukasReschke do not want the system to work on systems with that problem, fine. I am willing to put in the work but not if it's going to be for nothing in the end.

**Comment by MorrisJobke** [comment] 2017-01-09 14:00
> This is just something that is not under the control of me as a customer on a shared hosting service

But you as a user can complain to the admin to set it up properly. Even if you pay only a little doesn't mean you can't give them feedback to enhance their product (or switch to another one).



> If you, @LukasReschke do not want the system to work on systems with that problem, fine. I am willing to put in the work but not if it's going to be for nothing in the end.

The problem is, that with this approach we only would fix a symptom of 1 out of thousands or millions of servers. This is not good, because 1) we fix a symptom and not the cause, 2) only on a tiny fraction of the install base and 3) we add code that could break on all servers and we need to keep it stable and maintain it.

It's not that we don't want to have it working, but from our perspective it's also a ton of work and we also have limited time.

**Comment by mithodin** [comment] 2017-01-09 14:05
Okay, I get that. I guess I just need to keep updating my fork then until my provider decides to fix the problem.

**Comment by ChristophWurst** [comment] 2017-03-13 22:21
Closing this as "wontfix"

**Closed by ChristophWurst** 2017-03-13 22:21 UTC
Labels: wontfix
