### ISSUE TITLE
no app in context] Info: OCP\AppFramework\QueryException: Could not resolve state! Class state does not exist at <<closure>>

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/twofactor_totp#445] opened 2019-02-11 00:18 UTC
Steps to reproduce
since upgrade from Nextcloud 14.0.6 to 15.04
Expected behaviour
log should not be flooded with these messages
Actual behaviour
log will be flooed with these messages
-->

[no app in context] Info: OCP\AppFramework\QueryException: Could not resolve state! Class state does not exist at <<closure>>

 0. /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 119
    resolve("state")
 1. /var/www/html/nextcloud/lib/private/ServerContainer.php line 132
    query("state")
 2. /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 68
    query("state")
 3. /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 98
    buildClass(ReflectionClass  ... "})
 4. /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 119
    resolve("OCA\\TwoFactorTOTP\\Settings\\Personal")
 5. /var/www/html/nextcloud/lib/private/ServerContainer.php line 132
    query("OCA\\TwoFactorTOTP\\Settings\\Personal")
 6. /var/www/html/nextcloud/lib/private/Settings/Manager.php line 163
    query("OCA\\TwoFactorTOTP\\Settings\\Personal")
 7. /var/www/html/nextcloud/lib/private/Settings/Manager.php line 283
    getSettings("admin", "logging")
 8. /var/www/html/nextcloud/settings/Controller/AdminSettingsController.php line 73
    getAdminSettings("logging")
 9. /var/www/html/nextcloud/settings/Controller/CommonSettingsTrait.php line 126
    getSettings("logging")
10. /var/www/html/nextcloud/settings/Controller/AdminSettingsController.php line 65
    getIndexResponse("admin", "logging")
11. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
    index("logging")
12. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    executeController(OC\Settings\Cont ... {}, "index")
13. /var/www/html/nextcloud/lib/private/AppFramework/App.php line 118
    dispatch(OC\Settings\Cont ... {}, "index")
14. /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    main("OC\\Settings\\C ... r", "index", OC\AppFramework\ ... {}, {section: "loggi ... "})
15. <<closure>>
    __invoke({section: "loggi ... "})
16. /var/www/html/nextcloud/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {section: "loggi ... "})
17. /var/www/html/nextcloud/lib/base.php line 987
    match("/settings/admin/logging")
18. /var/www/html/nextcloud/index.php line 42
    handleRequest()

GET /settings/admin/logging
from xxxxxxx by admin at 2019-02-11T01:13:20+01:00

Server configuration detail
Operating system: Linux 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64
Webserver: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.1.25 (apache2handler)
Database: mysql 5.5.60
PHP version:
PHP Version => 7.2.10

Nextcloud version: 15.0.4
Updated from an older Nextcloud/ownCloud or fresh install: Upgrade from 14.0.6,

Where did you install Nextcloud from: Origine Source
Signing status
List of activated apps
Configuration (config/config.php)
Are you using external storage, if yes which one: no
Are you using encryption:
Are you using an external user-backend, if yes which one: no
Client configuration
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Operating system: Windows 10

**Comment by ChristophWurst** [comment] 2019-02-11 08:05
Fixed with https://github.com/nextcloud/twofactor_totp/pull/372. This patch will be released this week.

**Comment by ChristophWurst** [comment] 2019-02-11 08:05
Duplicate of https://github.com/nextcloud/twofactor_totp/issues/368

**Closed by ChristophWurst** 2019-02-11 08:05 UTC
