### ISSUE TITLE
Signature could not get checked.

### ISSUE THREAD

**Issue by gunph1ld** [nextcloud/twofactor_totp#146] opened 2017-02-26 16:33 UTC
Hi!

I was trying to install the app from the store and got this error
<img width="1002" alt="screen shot 2017-02-26 at 19 30 43" src="https://cloud.githubusercontent.com/assets/17044561/23341538/74dd8002-fc5a-11e6-966c-0ef0214cf690.png">

**Comment by MariusBluem** [comment] 2017-02-26 17:30
You are using Nextcloud 9 or 10 with the Owncloud App Store, right? 😕

**Comment by ChristophWurst** [comment] 2017-02-26 19:48
Hey @gunph1ld,

please provide more information about your setup so we can narrow down the problem 😉 

Thanks

**Comment by gunph1ld** [comment] 2017-02-26 20:15
Hey
I use owncloud-9.1.4-2.1
Go to Apps->Tools and try to install `TOTP TwoFactor (Google Authenticator) `

**Comment by MariusBluem** [comment] 2017-02-26 20:22
I am sorry. We are not supporting owncloud ... this repository is only developing the twofactor_totp app for Nextcloud :)

This is a duplicate of https://github.com/nextcloud/twofactor_totp/issues/142

**Comment by ChristophWurst** [comment] 2017-02-26 20:23
Alright, so this error is thrown because the app is signed for Nextcloud and therefore the verification fails on ownCloud. Recent versions of this app are incompatible with oc. You can now either use an outdated release of this app (missing security and usability features) or upgrade to Nextcloud 😉

**Closed by MariusBluem** 2017-02-26 20:22 UTC
Labels: needs info
