### ISSUE TITLE
Unable to login due to invalid QR code when TOTP is disabled, enforced and backup codes exist

### ISSUE THREAD

**Issue by PVince81** [nextcloud/twofactor_totp#1153] opened 2021-11-04 09:35 UTC
### Steps to reproduce
1. Setup Nextcloud
2. Create a user "alice"
3. Enable "twofactor_backupcodes" app
4. Enable "twofactor_totp" app
5. Login as admin and go to the security section in the settings page
6. Enable "Enforce two-factor authentication" and **don't forget** to click "save changes"
7. Log out
8. Login as "alice"
9. Setup TOTP and enter the code
10. Go to the security settings
11. Generate backup codes
12. Untick "Enable TOTP"
13. Log out
14. Login as "alice" again

### Expected behaviour
Valid QR code shown during TOTP setup.

### Actual behaviour
Invalid QR code generated during TOTP setup.
The endpoint https://vvortex.local/index.php/apps/twofactor_totp/settings/enable returns a 303 redirection to itself.

### Workaround
Ask the admin to run `update oc_twofactor_providers set enabled=0 where provider_id='backup_codes' and uid='alice';` to disable the backup codes provider.

### Server configuration

**Version:** Nextcloud 22.2.0.2

**List of activated apps:**

```
  - accessibility: 1.8.0
  - activity: 2.14.3
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - lookup_server_connector: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.10.0
  - photos: 1.4.0
  - provisioning_api: 1.12.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - systemtags: 1.12.0
  - text: 3.2.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_totp: 6.1.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.7.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
```

##### Server log (data/nextcloud.log)
No relevant log entries.

##### Browser log
<img width="754" alt="image" src="https://user-images.githubusercontent.com/277525/140290510-8cbb9d56-32d2-4107-b4a8-7c183a9b9f16.png">

**Comment by PVince81** [comment] 2021-11-04 09:45
note: it's not possible to disable the "backup_codes" provider with occ for some reason, so the SQL statement is needed as workaround

**Comment by PVince81** [comment] 2021-11-04 09:46
I've debugged into the code and found that here https://github.com/nextcloud/server/blob/v22.2.0/core/Middleware/TwoFactorMiddleware.php#L98 the provider list is retrieved. Usually if the list is empty, it would work fine or if the list contains both "totp" and "backup_codes".

But when only "backup_codes" is visible, it will throw a `TwoFactorAuthRequiredException`.

Now, the web UI itself does show the TOTP entry, so the logic for the provider list is likely different there, based on whether two factor is enforced or not. Maybe we need to align these ?

**Comment by PVince81** [comment] 2021-11-04 09:49
if I disable the twofactor_totp app now I see this:
<img width="247" alt="image" src="https://user-images.githubusercontent.com/277525/140292641-597e1f82-5b72-4e29-b2a3-ca18bc7cca8a.png">

so it seems there's a legal mechanism for logging in when enforced.

I'm not sure what the expected behavior is then when the app is enabled.
The user has disabled TOTP for themselves, so should the login flow hide the TOTP choice ?

**Comment by PVince81** [comment] 2021-11-04 09:51
I see two possibilities for this user who has disabled TOTP but backup codes exist:
1) login flow shows TOTP to allow the user to reenable it ?
or
2) login flow should only show backup codes approach

in the case of 1), we need to find a way for the middleware to still allow the SettingsController of TOTP to run

in the case of 2), we need to check whatever controller is providing the list of providers and removing the TOTP one when disabled

**Comment by ChristophWurst** [comment] 2021-11-04 10:11
Duplicate of https://github.com/nextcloud/twofactor_totp/issues/1147?

**Comment by PVince81** [comment] 2021-11-04 10:15
> Duplicate of #1147?

not sure as this is not about first login
can't be about first login because backup codes got created by the user

let's keep them separate for now, maybe the solution will fix both though...

@ChristophWurst any hint on the expected behavior at least ?

**Comment by PVince81** [comment] 2021-11-05 08:06
also broken on master

likely related to https://github.com/nextcloud/server/pull/28725/

**Comment by PVince81** [comment] 2021-11-05 08:41
I don't fully understand how it's supposed to work.
It seems the controller is detected in https://github.com/nextcloud/server/blob/master/core/Middleware/TwoFactorMiddleware.php#L101 but we still seem to want to block the controller instead of fully allowing it.

@LukasReschke can you help with more context ?
this is when forcing 2FA with only backup codes enabled.

**Comment by ChristophWurst** [comment] 2021-11-18 09:50
I can not reproduce this anymore after https://github.com/nextcloud/server/pull/29752

**Closed by ChristophWurst** 2021-11-18 09:50 UTC
Labels: bug, 1. to develop

**Comment by sn0wmanmj** [comment] 2021-11-23 08:26
Still doesn't work for me, even after applying nextcloud/server#29752. I don't know if it's related but after entering my credentials, before i even select a 2fa method, this appears in the logs: 
```
[PHP] Error: Undefined index: redirect_url at /var/www/html/nextcloud/core/templates/twofactorsetupselection.php#36

GET /index.php/login/setupchallenge
from [redacted] by 0BD0C313-28FD-4BCE-AC6B-C5357F25CF53 at 2021-11-23T09:15:26+01:00
```

**Comment by ChristophWurst** [comment] 2021-11-23 08:32
> Still doesn't work for me

What browser? Does the request to oc.js happen and does it work?

**Comment by sn0wmanmj** [comment] 2021-11-23 08:46
> What browser? Does the request to oc.js happen and does it work?

In Firefox and Chrome the request doesn't happen, but in Edge it happens and seems to work.

**Comment by ChristophWurst** [comment] 2021-11-23 08:55
Okay. Please open a new ticket, this must be yet another bug or regression.
