### ISSUE TITLE
Feature Request: option to not ask for 2fa token on the same computer

### ISSUE THREAD

**Issue by tessus** [nextcloud/twofactor_totp#272] opened 2018-09-12 00:14 UTC
### Feature Request

Other sites like Google allow you to check a box during the 2fa step so that you won't be asked for a 2fa token again on the same computer.

#### Summary

In many software environments there's the concept of trusted devices. Therefore it would make sense to be able to forego submitting an authentication code every time when using the same computer/browser.
One might argue that this weakens security, but apparently Google and other big companies don't think so.

**Comment by ChristophWurst** [comment] 2018-09-14 07:30
This is a duplicate of https://github.com/nextcloud/server/issues/2906. Having this feature in server rather than specific 2FA apps will make it available for all 2FA providers.

**Closed by ChristophWurst** 2018-09-14 07:30 UTC
