### ISSUE TITLE
 Unknown column 'state' in 'field list

### ISSUE THREAD

**Issue by jbacksch** [nextcloud/twofactor_totp#480] opened 2019-03-03 23:14 UTC
### Steps to reproduce
Login to nextcloud

### Expected behaviour
Successfull login

### Actual behaviour
Der Server konnte die Anfrage nicht fertig stellen.

Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an Deinen Server-Administrator.

Weitere Details können im Server-Protokoll gefunden werden.

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache/2.4.29

**Database:** MariaDB 10.1.38

**PHP version:** 7.2

**Version:** 15.0.5.3

**Updated from an older version or fresh install:** Update

**List of activated apps:** Standard +  Two Factor TOTP Provider 2.1.1

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => '...',
  'passwordsalt' => '...',
  'secret' => '...',
  'trusted_domains' =>
  array (
    0 => 'myhostname',
  ),
  'datadirectory' => '/srv/nextcloud/data',
  'overwrite.cli.url' => 'https://myhostname',
  'dbtype' => 'mysql',
  'version' => '15.0.5.3',
  'dbname' => '...',
  'dbhost' => '...',
  'dbtableprefix' => 'oc_',
  'dbuser' => '...',
  'dbpassword' => '...',
  'logtimezone' => 'UTC',
  'installed' => true,

  'lost_password_link' => '...',
  'logfile' => '/var/log/nextcloud.log',
  'loglevel' => 2,
  'theme' => '',
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'twofactor_enforced' => 'false',
  'twofactor_enforced_groups' =>
  array (
  ),
  'twofactor_enforced_excluded_groups' =>
  array (
  ),
);



```

#### Client configuration
**Browser:** all

**Operating system:** all

##### Server log (data/nextcloud.log)
```
An exception occurred while executing 'SELECT `id`, `user_id`, `secret`, `state` FROM `oc_twofactor_totp_secrets` WHERE `user_id` = ?' with params [\"username\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'state' in 'field list'"
```

**Comment by ChristophWurst** [comment] 2019-03-04 07:36
Is this a duplicate of https://github.com/nextcloud/twofactor_totp/issues/411?

**Comment by jbacksch** [comment] 2019-03-04 07:48
Try to fix the issue with 

- deinstalling the app

- clean up the migrations table

- reinstall app again 

does not help.

```
MariaDB [(none)]> use nextcloud;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [nextcloud]> select * from oc_migrations where app like '%twofactor%' ;
+----------------+--------------------------+
| app            | version                  |
+----------------+--------------------------+
| twofactor_totp | 010501Date20181018124436 |
+----------------+--------------------------+
1 row in set (0.00 sec)

MariaDB [nextcloud]> delete from oc_migrations where app='twofactor_totp';
Query OK, 1 row affected (0.01 sec)

MariaDB [nextcloud]> select * from oc_migrations where app like '%twofactor%' ;
Empty set (0.00 sec)
```

**Comment by ChristophWurst** [comment] 2019-03-04 07:49
Of course it does not help: https://github.com/nextcloud/twofactor_totp/blob/37ced585df640dc395dfddf0da7c66de1358d786/lib/Migration/Version010501Date20181018124436.php#L45

**Comment by jbacksch** [comment] 2019-03-04 07:53
Should we add this column 'state' manually in the DB to fix this issue?

**Comment by ChristophWurst** [comment] 2019-03-04 07:56
No, the migration should be fixed instead, otherwise other users will run into this problem as well.

I'll have a look soonish and it would be great if you could test my patch!

**Comment by jbacksch** [comment] 2019-03-04 11:46
Thanks. You're welcome. Waiting for your patch.

**Comment by ChristophWurst** [comment] 2019-03-04 12:22
Let's continue in #411

**Closed by ChristophWurst** 2019-03-04 12:22 UTC
Labels: needs info
