### ISSUE TITLE
Undefined index: redirect_url at /var/www/html/core/templates/twofactorsetupselection.php

### ISSUE THREAD

**Issue by EvgenyKotov** [nextcloud/twofactor_totp#1133] opened 2021-07-15 13:30 UTC
### Steps to reproduce
1. New User setup
2. Login 
3. Click "TOTP "

### Expected behaviour
Tell us what should happen

Browser Console:

POST https://nc.ueberherrn.de/apps/twofactor_totp/settings/enable     [HTTP/2 500 Internal Server Error 162ms]

Uncaught (in promise) Error: Request failed with status code 500

### Actual behaviour
Tell us what happens instead

### Server configuration

Docker 

**Operating system**:

Ubuntu

**Version:** (see admin page)

20.0.11

**Updated from an older version or fresh install:**

**List of activated apps:**
 - activity: 2.13.4
  - admin_audit: 1.10.0
  - bruteforcesettings: 2.2.0
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - customproperties: 2.0.3
  - dashboard: 7.0.0
  - dav: 1.16.2
  - documentserver_community: 0.1.10
  - extract: 1.3.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_accesscontrol: 1.10.2
  - files_antivirus: 3.2.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - flow_notifications: 1.0.3
  - geoblocker: 0.5.1
  - groupfolders: 8.2.2
  - groupquota: 0.1.6
  - guests: 1.6.3
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.4.2
  - orcid: 1.1.1
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - ransomware_protection: 1.11.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - suspicious_login: 3.2.1
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflow_ocr: 1.20.2
  - workflowengine: 2.2.0

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
 - activity: 2.13.4
  - admin_audit: 1.10.0
  - bruteforcesettings: 2.2.0
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - customproperties: 2.0.3
  - dashboard: 7.0.0
  - dav: 1.16.2
  - documentserver_community: 0.1.10
  - extract: 1.3.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_accesscontrol: 1.10.2
  - files_antivirus: 3.2.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - flow_notifications: 1.0.3
  - geoblocker: 0.5.1
  - groupfolders: 8.2.2
  - groupquota: 0.1.6
  - guests: 1.6.3
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.4.2
  - orcid: 1.1.1
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - ransomware_protection: 1.11.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - suspicious_login: 3.2.1
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflow_ocr: 1.20.2
  - workflowengine: 2.2.0
Disabled:
  - encryption
  - files_external
  - user_ldap

**The content of config/config.php:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "1": "nc.ueberherrn.de",
            "ds.ueberherrn.de": ""
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.11.1",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "0": "filelocking.enabled\u2019 => \u2018true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "allow_local_remote_servers": true,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [
            "FW Berus EB",
            "FW Felsberg EB",
            "FW S\u00fcd EB",
            "FW_Altforweiler_EB"
        ],
        "onlyoffice": {
            "verify_peer_off": true,
            "StorageUrl": {
                "value=https:\/\/nc.ueberherrn.de\/": ""
            }
        },
        "app_install_overwrite": [
            "files_retention"
        ],
        "theme": "",
        "loglevel": 2
    }
}


Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
"system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": ",
        "secret": "",
        "trusted_domains": {
            "0": "localhost",
            "1": "",
            "ds.ueberherrn.de": ""
        },
        "datadirectory": "\/var\/www\/html\/data",
        "dbtype": "mysql",
        "version": "20.0.11.1",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "",
        "dbhost": "",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "",
        "dbpassword": "",
        "installed": true,
        "instanceid": "ocsc1hloe1gu",
        "overwriteprotocol": "https",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "cloud",
        "mail_domain": "",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "",
        "mail_smtpport": "25",
        "mail_smtpname": "",
        "mail_smtppassword": "",
        "maintenance": false,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "0": "filelocking.enabled\u2019 => \",
        "redis": {
            "host": "",
            "password": "",
            "port": 6379
        },
        "allow_local_remote_servers": true,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [
           
        ],
        "onlyoffice": {
            "verify_peer_off": true,
            "StorageUrl": {
                "value=https:\/\/\/": ""
            }
        },
        "app_install_overwrite": [
            "files_retention"
        ],
        "theme": "",
        "loglevel": 2
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.13.4",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "204"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "2.2.0",
            "types": ""
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "logging"
        },
        "contactsinteraction": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "dav"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "default_encryption_module": "OC_DEFAULT_MODULE",
            "encryption_enabled": "no",
            "installedat": "1604392461.6059",
            "lastcron": "1626354903",
            "lastupdateResult": "{\"version\":\"21.0.3.1\",\"versionstring\":\"Nextcloud 21.0.3\",\"url\":\"https:\\\/\\\/download.nextcloud.com\\\/server\\\/releases\\\/nextcloud-21.0.3.zip\",\"web\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/21\\\/admin_manual\\\/maintenance\\\/upgrade.html\",\"changes\":\"https:\\\/\\\/updates.nextcloud.com\\\/changelog_server\\\/?version=21.0.3\",\"autoupdater\":\"1\",\"eol\":\"0\"}",
            "lastupdatedat": "1626354144",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "shareapi_allow_group_sharing": "no",
            "shareapi_allow_links": "yes",
            "shareapi_allow_public_upload": "no",
            "shareapi_allow_resharing": "no",
            "shareapi_default_expire_date": "yes",
            "shareapi_default_internal_expire_date": "yes",
            "shareapi_default_permission_candelete": "yes",
            "shareapi_default_permissions": "31",
            "shareapi_enable_link_password_by_default": "yes",
            "shareapi_enforce_expire_date": "yes",
            "shareapi_enforce_internal_expire_date": "yes",
            "shareapi_enforce_links_password": "yes",
            "shareapi_exclude_groups": "yes",
            "shareapi_exclude_groups_list": "[]",
            "shareapi_internal_enforce_expire_date": "yes",
            "shareapi_internal_expire_after_n_days": "7",
            "theming.variables": "10762a0b6b35fb99325fb2d89b80e08d",
            "updater.secret.created": "1625756689",
            "vendor": "nextcloud"
        },
        "customproperties": {
            "enabled": "yes",
            "installed_version": "2.0.3",
            "types": ""
        },
        "dashboard": {
            "enabled": "yes",
            "installed_version": "7.0.0",
            "types": ""
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "generateBirthdayCalendar": "no",
            "installed_version": "1.16.2",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "sendEventReminders": "no",
            "sendInvitations": "no",
            "types": "filesystem"
        },
        "documentserver_community": {
            "enabled": "yes",
            "installed_version": "0.1.10",
            "types": "filesystem"
        },
        "encryption": {
            "enabled": "no",
            "encryptHomeStorage": "1",
            "installed_version": "2.8.1",
            "masterKeyId": "master_7c33218f",
            "publicShareKeyId": "pubShare_7c33218f",
            "recoveryKeyId": "recoveryKey_7c33218f",
            "types": "filesystem"
        },
        "end_to_end_encryption": {
            "enabled": "no",
            "installed_version": "1.6.2",
            "types": "dav,filesystem"
        },
        "extract": {
            "enabled": "yes",
            "installed_version": "1.3.2",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.10.2",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "filesystem",
            "watermark_allGroups": "no",
            "watermark_allGroupsList": "",
            "watermark_allTags": "no",
            "watermark_allTagsList": "",
            "watermark_enabled": "yes",
            "watermark_linkAll": "yes",
            "watermark_linkRead": "no",
            "watermark_linkSecure": "no",
            "watermark_linkTags": "no",
            "watermark_linkTagsList": "",
            "watermark_shareAll": "yes",
            "watermark_shareRead": "yes",
            "watermark_text": "{userId}"
        },
        "files_accesscontrol": {
            "enabled": "yes",
            "installed_version": "1.10.2",
            "types": "filesystem"
        },
        "files_antivirus": {
            "av_cmd_options": "",
            "av_host": "cloud-av",
            "av_infected_action": "delete",
            "av_max_file_size": "-1",
            "av_mode": "daemon",
            "av_path": "\/usr\/bin\/clamscan",
            "av_port": "3310",
            "av_socket": "\/var\/run\/clamav\/clamd.ctl",
            "av_stream_max_length": "26214400",
            "enabled": "yes",
            "installed_version": "3.2.1",
            "types": "filesystem,dav"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "2.0.1",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "0.17.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "no",
            "installed_version": "1.12.2",
            "lookupServerEnabled": "no",
            "lookupServerUploadEnabled": "no",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.9.0",
            "types": "logging"
        },
        "flow_notifications": {
            "enabled": "yes",
            "installed_version": "1.0.3",
            "types": ""
        },
        "geoblocker": {
            "choosenCountries": "DE, ",
            "choosenWhiteBlackList": "1",
            "chosenService": "2",
            "enabled": "yes",
            "installed_version": "0.5.1",
            "logWithCountryCode": "1",
            "logWithIpAddress": "1",
            "rir_data_db_date": "2021-07-09",
            "rir_data_db_version": "0",
            "rir_data_service_status": "3",
            "types": ""
        },
        "groupfolders": {
            "enabled": "yes",
            "installed_version": "8.2.2",
            "types": "filesystem,dav"
        },
        "groupquota": {
            "enabled": "yes",
            "installed_version": "0.1.6",
            "types": "filesystem"
        },
        "guests": {
            "allow_external_storage": "false",
            "enabled": "yes",
            "hide_users": "true",
            "installed_version": "1.6.3",
            "types": "authentication",
            "usewhitelist": "true",
            "whitelist": "files_trashbin,files_sharing,files_texteditor,text,activity,firstrunwizard,notifications,dashboard,user_status,weather_status,customproperties,files_pdfviewer,files_versions,end_to_end_encryption,encryption,viewer,groupfolders"
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.5.0",
            "levels": "01000",
            "live": "",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.8.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "authentication"
        },
        "officeonline": {
            "enabled": "no",
            "installed_version": "1.0.0",
            "types": "filesystem,dav,prevent_group_restriction"
        },
        "onlyoffice": {
            "DocumentServerInternalUrl": "https:\/\/\/",
            "DocumentServerUrl": "https:\/\/\/",
            "StorageUrl": "https:\/\/\/",
            "customizationChat": "true",
            "customizationCompactHeader": "true",
            "customizationFeedback": "true",
            "customizationForcesave": "false",
            "customizationHelp": "true",
            "customizationReviewDisplay": "original",
            "customizationToolbarNoTabs": "true",
            "defFormats": "{\"csv\":\"false\",\"doc\":\"false\",\"docm\":\"false\",\"docx\":\"true\",\"dotx\":\"false\",\"epub\":\"false\",\"html\":\"false\",\"odp\":\"false\",\"ods\":\"false\",\"odt\":\"false\",\"otp\":\"false\",\"ots\":\"false\",\"ott\":\"false\",\"pdf\":\"false\",\"potm\":\"false\",\"potx\":\"false\",\"ppsm\":\"false\",\"ppsx\":\"false\",\"ppt\":\"false\",\"pptm\":\"false\",\"pptx\":\"true\",\"rtf\":\"false\",\"txt\":\"false\",\"xls\":\"false\",\"xlsm\":\"false\",\"xlsx\":\"true\",\"xltm\":\"false\",\"xltx\":\"false\"}",
            "demo": "{\"available\":false,\"enabled\":false,\"start\":{\"date\":\"2020-11-11 09:01:34.466314\",\"timezone_type\":3,\"timezone\":\"UTC\"}}",
            "editFormats": "{\"csv\":\"true\",\"odp\":\"false\",\"ods\":\"false\",\"odt\":\"false\",\"rtf\":\"false\",\"txt\":\"true\"}",
            "enabled": "yes",
            "groups": "[]",
            "installed_version": "6.4.2",
            "jwt_secret": "",
            "preview": "false",
            "sameTab": "true",
            "settings_error": "",
            "types": "filesystem",
            "verify_peer_off": "false"
        },
        "orcid": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "password_policy": {
            "enabled": "yes",
            "enforceHaveIBeenPwned": "1",
            "enforceNumericCharacters": "1",
            "enforceSpecialCharacters": "1",
            "enforceUpperLowerCase": "1",
            "installed_version": "1.10.1",
            "maximumLoginAttempts": "5",
            "minLength": "12",
            "types": "authentication"
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.2.3",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "readableLocation": "de",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "prevent_group_restriction"
        },
        "ransomware_protection": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "notefile_additions": "[]",
            "notefile_exclusions": "[]",
            "notes_include_biased": "yes",
            "types": "logging"
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "0.8.0",
            "types": ""
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "enforcePasswordProtection": "yes",
            "installed_version": "1.10.0",
            "types": "filesystem"
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "last_report": "{\"id\":\"ocsc1hloe1gu\",\"items\":[[\"server\",\"version\",\"20.0.5.2\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"\\\\OC\\\\Memcache\\\\APCu\"],[\"server\",\"memcache.distributed\",\"\\\\OC\\\\Memcache\\\\Redis\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"\\\\OC\\\\Memcache\\\\Redis\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"cron\"],[\"php\",\"version\",\"7.4.14\"],[\"php\",\"memory_limit\",536870912],[\"php\",\"max_execution_time\",0],[\"php\",\"upload_max_filesize\",2097152],[\"database\",\"type\",\"mysql\"],[\"database\",\"version\",\"10.5.6\"],[\"database\",\"size\",2998272],[\"apps\",\"accessibility\",\"1.6.0\"],[\"apps\",\"activity\",\"2.13.4\"],[\"apps\",\"admin_audit\",\"1.10.0\"],[\"apps\",\"bruteforcesettings\",\"2.1.0\"],[\"apps\",\"cloud_federation_api\",\"1.3.0\"],[\"apps\",\"comments\",\"1.10.0\"],[\"apps\",\"contactsinteraction\",\"1.1.0\"],[\"apps\",\"customproperties\",\"1.0.1\"],[\"apps\",\"dashboard\",\"7.0.0\"],[\"apps\",\"dav\",\"1.16.2\"],[\"apps\",\"documentserver_community\",\"0.1.9\"],[\"apps\",\"encryption\",\"disabled\"],[\"apps\",\"end_to_end_encryption\",\"disabled\"],[\"apps\",\"extract\",\"1.3.1\"],[\"apps\",\"federatedfilesharing\",\"1.10.2\"],[\"apps\",\"federation\",\"1.10.1\"],[\"apps\",\"files\",\"1.15.0\"],[\"apps\",\"files_accesscontrol\",\"1.10.2\"],[\"apps\",\"files_antivirus\",\"3.2.0\"],[\"apps\",\"files_pdfviewer\",\"2.0.1\"],[\"apps\",\"files_rightclick\",\"0.17.0\"],[\"apps\",\"files_sharing\",\"1.12.2\"],[\"apps\",\"files_trashbin\",\"1.10.1\"],[\"apps\",\"files_versions\",\"1.13.0\"],[\"apps\",\"files_videoplayer\",\"1.9.0\"],[\"apps\",\"firstrunwizard\",\"2.9.0\"],[\"apps\",\"flow_notifications\",\"1.0.3\"],[\"apps\",\"geoblocker\",\"0.4.6\"],[\"apps\",\"groupfolders\",\"8.2.1\"],[\"apps\",\"groupquota\",\"0.1.5\"],[\"apps\",\"guests\",\"1.6.3\"],[\"apps\",\"logreader\",\"2.5.0\"],[\"apps\",\"lookup_server_connector\",\"1.8.0\"],[\"apps\",\"nextcloud_announcements\",\"1.9.0\"],[\"apps\",\"notifications\",\"2.8.0\"],[\"apps\",\"oauth2\",\"1.8.0\"],[\"apps\",\"officeonline\",\"disabled\"],[\"apps\",\"onlyoffice\",\"6.4.2\"],[\"apps\",\"orcid\",\"1.1.1\"],[\"apps\",\"password_policy\",\"1.10.1\"],[\"apps\",\"photos\",\"1.2.3\"],[\"apps\",\"privacy\",\"1.4.0\"],[\"apps\",\"provisioning_api\",\"1.10.0\"],[\"apps\",\"ransomware_protection\",\"1.10.1\"],[\"apps\",\"recommendations\",\"0.8.0\"],[\"apps\",\"serverinfo\",\"1.10.0\"],[\"apps\",\"settings\",\"1.2.0\"],[\"apps\",\"sharebymail\",\"1.10.0\"],[\"apps\",\"support\",\"1.3.0\"],[\"apps\",\"survey_client\",\"1.8.0\"],[\"apps\",\"suspicious_login\",\"3.2.1\"],[\"apps\",\"systemtags\",\"1.10.0\"],[\"apps\",\"text\",\"3.1.0\"],[\"apps\",\"theming\",\"1.11.0\"],[\"apps\",\"twofactor_backupcodes\",\"1.9.0\"],[\"apps\",\"twofactor_totp\",\"5.0.0\"],[\"apps\",\"updatenotification\",\"1.10.0\"],[\"apps\",\"user_status\",\"1.0.1\"],[\"apps\",\"viewer\",\"1.4.0\"],[\"apps\",\"weather_status\",\"1.0.0\"],[\"apps\",\"wopi\",\"disabled\"],[\"apps\",\"workflow_ocr\",\"1.20.2\"],[\"apps\",\"workflow_script\",\"disabled\"],[\"apps\",\"workflowengine\",\"2.2.0\"],[\"stats\",\"num_files\",1464],[\"stats\",\"num_users\",5],[\"stats\",\"num_storages\",6],[\"stats\",\"num_storages_local\",1],[\"stats\",\"num_storages_home\",5],[\"stats\",\"num_storages_other\",0],[\"stats\",\"num_comments\",0],[\"stats\",\"num_comment_markers\",0],[\"stats\",\"num_systemtags\",0],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",7],[\"files_sharing\",\"num_shares_user\",2],[\"files_sharing\",\"num_shares_groups\",0],[\"files_sharing\",\"num_shares_link\",4],[\"files_sharing\",\"num_shares_link_no_password\",4],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"files_sharing\",\"permissions_3_17\",\"4\"],[\"files_sharing\",\"permissions_4_17\",\"1\"],[\"files_sharing\",\"permissions_0_31\",\"2\"],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"yes\"]]}",
            "last_sent": "1625152502",
            "types": ""
        },
        "suspicious_login": {
            "enabled": "yes",
            "installed_version": "3.2.1",
            "types": "authentication"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "logging"
        },
        "text": {
            "enabled": "yes",
            "installed_version": "3.1.0",
            "types": "dav"
        },
        "theming": {
            "backgroundMime": "image\/jpeg",
            "cachebuster": "20",
            "enabled": "yes",
            "faviconMime": "image\/png",
            "imprintUrl": "https:\/\/ueberherrn.de\/impressum",
            "installed_version": "1.11.0",
            "logoMime": "image\/png",
            "logoheaderMime": "image\/png",
            "name": "Gemeinde \u00dcberherrn",
            "privacyUrl": "https:\/\/ueberherrn.de\/datenschutz\/",
            "slogan": "\u00dcberherrn ein kleines St\u00fcck Europa",
            "types": "logging",
            "url": "https:\/\/www.ueberherrn.de"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": ""
        },
        "twofactor_totp": {
            "enabled": "yes",
            "installed_version": "5.0.0",
            "types": ""
        },
        "updatenotification": {
            "bruteforcesettings": "2.2.0",
            "core": "21.0.3.1",
            "customproperties": "2.0.3",
            "documentserver_community": "0.1.10",
            "enabled": "yes",
            "extract": "1.3.2",
            "files_accesscontrol": "1.10.2",
            "files_antivirus": "3.2.1",
            "flow_notifications": "1.0.3",
            "geoblocker": "0.5.1",
            "groupfolders": "8.2.2",
            "groupquota": "0.1.6",
            "guests": "1.6.3",
            "installed_version": "1.10.0",
            "onlyoffice": "6.4.2",
            "ransomware_protection": "1.11.0",
            "types": "",
            "update_check_errors": "0",
            "workflow_ocr": "1.20.2"
        },
        "user_status": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": ""
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "weather_status": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "wopi": {
            "enabled": "no",
            "installed_version": "3.5.6",
            "types": "filesystem,dav,prevent_group_restriction"
        },
        "workflow_ocr": {
            "enabled": "yes",
            "installed_version": "1.20.2",
            "types": "filesystem"
        },
        "workflow_script": {
            "enabled": "no",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.2.0",
            "types": "filesystem"
        }
    }

#### Client configuration
**Browser:**
Chrome + Firefox
**Operating system:**
Win 10

#### Server Log
 Warning  suspicious_login   Detected a login from a suspicious login. user=j.libera@ueberherrn.de ip=212.88.131.26 strategy=ipv4                                                                                2021-07-15T13:14:10+00:00

  Error    PHP                Error: Undefined index: redirect_url at /var/www/html/core/templates/twofactorsetupselection.php#36 at lib/private/Log/ErrorHandler.php line 91                                     2021-07-15T13:14:11+00:00

                              0. core/templates/twofactorsetupselection.php line 36
                                 OC\Log\ErrorHandler::onError(
                                   8,
                                   "Undefined index: redirect_url",
                                   "\/var\/www\/html\/core\/templates\/twofactorsetupselection.php",
                                   36,
                                   {file:"\/var\/www\/html\/core\/templates\/twofactorsetupselection.php",additionalParams:{providers:{totp:OCA\TwoFactorTOTP\Provider\TotpP ... "}
                                 )
                              1. lib/private/Template/Base.php line 180
                                 include("\/var\/www\/html\/core\/templates\/twofactorsetupselection.php")
                              2. lib/private/Template/Base.php line 150
                                 OC\Template\Base->load(
                                   "\/var\/www\/html\/core\/templates\/twofactorsetupselection.php",
                                   {providers:{totp:OCA\TwoFactorTOTP\Provider\TotpProvider {}},logout_url:"\/logout?requesttoken=xqIy9aBzptvXJqoGwa5MSc2JSo0Zc4L0ULXDOGqA4yU%3D%3 ... "}
                                 )
                              3. lib/private/legacy/OC_Template.php line 180
                                 OC\Template\Base->fetchPage({providers:{totp:OCA\TwoFactorTOTP\Provider\TotpProvider {}},logout_url:"\/logout?requesttoken=xqIy9aBzptvXJqoGwa5MSc2JSo0Zc4L0ULXDOGqA4yU ... "})
                              4. lib/public/AppFramework/Http/TemplateResponse.php line 210
                                 OC_Template->fetchPage({providers:{totp:OCA\TwoFactorTOTP\Provider\TotpProvider {}},logout_url:"\/logout?requesttoken=xqIy9aBzptvXJqoGwa5MSc2JSo0Zc4L0ULXDOGqA4yU%3D%3 ... "})
                              5. lib/private/AppFramework/Http/Dispatcher.php line 123
                                 OCP\AppFramework\Http\TemplateResponse->render(

                                 )
                              6. lib/private/AppFramework/App.php line 152
                                 OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Controller\TwoFactorChallengeController {}, "setupProviders")
                              7. lib/private/Route/Router.php line 309
                                 OC\AppFramework\App::main(
                                   "OC\\Core\\Controller\\TwoFactorChallengeController",
                                   "setupProviders",
                                   OC\AppFramework\DependencyInjection\DIContainer {},
                                   {_route:"core.TwoFactorChallenge.setupProviders"}
                                 )
                              8. lib/base.php line 1008
                                 OC\Route\Router->match("\/login\/setupchallenge")
                              9. index.php line 37
                                 OC::handleRequest(

                                 )

**Comment by ChristophWurst** [comment] 2021-07-15 18:52
Duplicate of https://github.com/nextcloud/server/issues/21968

**Closed by ChristophWurst** 2021-07-15 18:52 UTC
