### ISSUE TITLE
IP addresses exception list in TOTP

### ISSUE THREAD

**Issue by jsalatiel** [nextcloud/twofactor_totp#141] opened 2017-02-18 10:22 UTC
It would be nice if we could skip TOTP when logging from some IP range or host
Example: If i am on the internal network, i'd like to be able to use just my password to login, but if i am on internet i'd like to be asked for the TOTP.

I was thinking something like this in admin page:

TOTP ip exception list: '192.168.0.0/16 ; localhost ; somehost.somedomain.com'

**Comment by ChristophWurst** [comment] 2017-02-20 06:31
Hey,

this is a duplicate of https://github.com/nextcloud/server/issues/2035. Let's continue there 😉

**Closed by ChristophWurst** 2017-02-20 06:31 UTC
