### ISSUE TITLE
Exclude IP ranges

### ISSUE THREAD

**Issue by Somebodyisnobody** [nextcloud/twofactor_totp#762] opened 2019-12-16 19:26 UTC
### Feature Request
It would be nice if I could exclude certain IP ranges from TOTP, e.g. my local home network, but traffic from the Internet or VPN still needs TOTP.

#### Summary

Exclude specific IP ranges from TOTP authentication by mark them as trusted.

**Comment by ChristophWurst** [comment] 2019-12-16 19:40
Duplicate of #141 

See https://github.com/nextcloud/server/issues/2035

**Comment by Somebodyisnobody** [comment] 2019-12-16 19:41
It's a server-issue?!

**Closed by ChristophWurst** 2019-12-16 19:40 UTC

**Comment by ChristophWurst** [comment] 2019-12-16 19:51
yes?!
