### ISSUE TITLE
Enable/Disable 2FA by IP-ranges

### ISSUE THREAD

**Issue by Toraih** [nextcloud/twofactor_totp#593] opened 2019-06-18 13:49 UTC
### Feature Request

Allow to define an IP-range where 2FA is disabled

#### Summary

Since the clients who can connect to our company-LAN are already pre-authenticated (Radius/AD), we like to disable the 2FA for comfort reasons.
(only about quarter up to a third of our employes use it outside of our LAN, the others are a little annoyed to be forced to use 2FA, which is understandable)

**Comment by ChristophWurst** [comment] 2019-06-18 13:59
Duplicate of https://github.com/nextcloud/server/issues/2035 :)

**Comment by Toraih** [comment] 2019-06-18 13:59
Oops, this is an duplicate of #534 resp. nextcloud/server#2035
moving there...

**Closed by ChristophWurst** 2019-06-18 13:59 UTC
