### ISSUE TITLE
Cannot installed with PHP 7.1

### ISSUE THREAD

**Issue by timscha** [nextcloud/twofactor_totp#104] opened 2016-12-14 11:30 UTC
Hello!

I used your app without any problems on PHP 7.0. Now I switched to 7.1 and got the message:

"Die App kann nicht installiert werden, weil die folgenden Abhängigkeiten nicht erfüllt sind:

    PHP with a version lower than 7.0 is required."

The app works without problems - I only got this message on the enabled apps.

**Comment by ChristophWurst** [comment] 2016-12-14 12:37
Duplicate of https://github.com/nextcloud/twofactor_totp/issues/88 and will be fixed soon, see https://github.com/nextcloud/twofactor_totp/pull/99. Could you help testing the app with php7.1? I still have 7.0.14. on my development machine.

**Closed by ChristophWurst** 2016-12-14 12:37 UTC

**Comment by timscha** [comment] 2016-12-14 12:39
Sorry, don't saw the duplicate.
I can confirm it's working smoothly with 7,1

**Comment by ChristophWurst** [comment] 2016-12-18 21:54
@timscha feel free to test the nightly build at https://apps.nextcloud.com/apps/twofactor_totp which now allows 7.1 and submit your rating if you like the app 😉
