### ISSUE TITLE
[Suggestion] Allow to skip TOTP if the request comes from a whitelist

### ISSUE THREAD

**Issue by agdg** [nextcloud/twofactor_totp#188] opened 2017-08-17 20:15 UTC
I think it will be nice to be able to skip the TOTP system if the request comes from a whitelist IP or network, such as: 192.168.0.0/24, 192.168.1.20/32... Obviously, the idea is that the admin can configure a global whitelist, but it would also be interesting if the user can configure his own whitelist.

For example, it is useful to avoid using token on your local network.

**Comment by Trevelian** [comment] 2017-08-19 15:01
Hello,

I just come here to write the same things. twofactor_totp is great but be in a local network can be considered like the second factor of authentication when the password is entered.

**Comment by akeilox** [comment] 2017-08-19 16:53
+1 on being able to whitelist a subnet like 192.168.0.0/24 etc

**Comment by ChristophWurst** [comment] 2017-08-21 05:56
Hi,

this is a duplicate of https://github.com/nextcloud/twofactor_totp/issues/141 and https://github.com/nextcloud/server/issues/2035.

**Closed by ChristophWurst** 2017-08-21 05:56 UTC
