### ISSUE TITLE
occ twofactorauth:state not working

### ISSUE THREAD

**Issue by zippytiff** [nextcloud/twofactor_totp#524] opened 2019-03-27 10:16 UTC
### Steps to reproduce
1. run occ twofactorauth:state <username>

### Expected behaviour
Tell us what should happen

I imagined this would say if the user had enabled 2FA, in this testing I know the user im checking has enabled 2FA and uses it

### Actual behaviour
Tell us what happens instead

Two-factor authentication is not enabled for user <Username>

### Server configuration

15.0.5

**Comment by ChristophWurst** [comment] 2019-03-27 10:20
> Steps to reproduce

You're missing the steps before you run the command. This bug (should it be one) is not reproducible this way.

**Comment by ChristophWurst** [comment] 2019-03-27 10:21
E.g. when did the user enable TOTP?

**Comment by zippytiff** [comment] 2019-03-27 10:23
Hi

Thanks, but how do you mean ?

All I do is run that occ command e.g occ user:list and it gives me a list

Regards

Tim

**Comment by ChristophWurst** [comment] 2019-03-27 10:26
"Steps to reproduce" are meant to be used for us to reproduce the problem on a clean (new) installation. If I just run the command, I won't see much as a user (should I even have created one) won't have any 2FA configured.

**Comment by zippytiff** [comment] 2019-03-27 10:42
Ah I see

Well, ill try


-          Running 15.0.5, upgraded from 13.0.2

-          The TOTP app is installed from 13.0.2 days

-          TOTP has been enabled, activated and verified by the relevant users, including the user im looking to check ‘enabled’ against

-          TOTP app upgraded thru 14 then 15.0.5

-          Looking to use the new occ check state command to verify the user (who is me using a test account) has TOTP enabled

Let me know what else I can provide

ZT

**Comment by ChristophWurst** [comment] 2019-03-27 12:27
Skipping major versions is not supported. You should have upgraded through 14.

**Comment by ChristophWurst** [comment] 2019-03-27 12:28
Nvm, you mention 14 below.

**Comment by zippytiff** [comment] 2019-03-27 12:40
Hi

I did

13 > 14 > 15

At each stage I updated the relevant apps

Hope that helps

I’m happy to run any debug etc, just let me know

ZT

On 27 Mar 2019, at 12:27, Christoph Wurst <notifications@github.com<mailto:notifications@github.com>> wrote:


Skipping major versions is not supported. You should have upgraded through 14.

**Comment by ChristophWurst** [comment] 2019-03-27 12:44
[Nextcloud 14](https://github.com/nextcloud/server/blob/ad06248889aff2f42b7c4c1aa09bc7901fe29730/lib/private/Authentication/TwoFactorAuth/Manager.php#L150-L180) to [Nextcloud 16](https://github.com/nextcloud/server/blob/86594e8c18123db6696f4cedfc0578d036ad5dd6/lib/private/Authentication/TwoFactorAuth/Manager.php#L136-L166) have logic in place the updates the provider registry for 2FA apps that have been enabled since previous version.

Did the user you were checking the state for log into Nextcloud since the upgrade to Nextcloud 14?

**Comment by zippytiff** [comment] 2019-03-27 12:45
Hi

No I didn’t check the state feature at 14, as that was a just a ‘pass-thru’ update

ZT

**Comment by ChristophWurst** [comment] 2019-03-27 12:47
But has the user you ran the state command for logged into your instance since Nextcloud 13?

**Comment by zippytiff** [comment] 2019-03-27 12:48
Yes,

In fact I removed the 2FA off that user and re-added

Still the same

ZT

**Comment by zippytiff** [comment] 2019-03-27 14:40
Hi

An interesting observation, which I think points to a bigger issue I may have

I was able to get ‘state’ for another user

When I tried user:info on the working ‘state’ users and non-working ‘state’ users, I could see that for the non-working ‘state’ users various other attributes are blank, namly:


-          Last login : 1970…

-          Not a member of any groups

Does this help point to anything ?

Thanks for the excellent responsiveness regards this

ZT

**Comment by ChristophWurst** [comment] 2019-03-27 14:53
This is indeed unexpected. Maybe there is something wrong with your setup. Double-check the admin docs for this: https://docs.nextcloud.com/server/stable/admin_manual/

**Comment by ChristophWurst** [comment] 2019-08-07 13:14
Closing as no further input was given. Let me know if this is still a problem, then I can reopen.

**Closed by ChristophWurst** 2019-08-07 13:14 UTC
Labels: 0. to triage, bug, needs info
